<?xml version="1.0"?>

<robot name="tracer_gazebo" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="diff_drive_control">
        <gazebo>
            <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
                <ros>
                    <namespace>${robot_namespace}</namespace>
                </ros>
                <!-- Update rate in Hz -->
                <update_rate>50</update_rate>
                <!-- wheels -->
                <left_joint>left_wheel_joint</left_joint>
                <right_joint>right_wheel_joint</right_joint>
                <!-- kinematics -->
                <wheel_separation>${wheelbase}</wheel_separation>
                <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                <!-- limits -->
                <max_wheel_torque>20</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>
                <!-- input -->
                <command_topic>cmd_vel</command_topic>
                <!-- output -->
                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>
                <odometry_topic>odom</odometry_topic>
                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_link</robot_base_frame>
            </plugin>
            <plugin name="gazebo_ros_joint_state_publisher"
                filename="libgazebo_ros_joint_state_publisher.so">
                <ros>
                    <namespace>${robot_namespace}</namespace>
                </ros>
                <!-- Update rate in Hertz -->
                <update_rate>10</update_rate>
                <!-- Name of joints in the model whose states will be published. -->
                <joint_name>front_right_castor_joint</joint_name>
                <joint_name>front_right_wheel_joint</joint_name>
                <joint_name>front_left_castor_joint</joint_name>
                <joint_name>front_left_wheel_joint</joint_name>
                <joint_name>rear_right_castor_joint</joint_name>
                <joint_name>rear_right_wheel_joint</joint_name>
                <joint_name>rear_left_castor_joint</joint_name>
                <joint_name>rear_left_wheel_joint</joint_name>
            </plugin>
        </gazebo>
    </xacro:macro>
</robot>